Catch exceptions in getGenes

diff --git a/bin/updateData b/bin/updateData
--- a/bin/updateData
+++ b/bin/updateData
@@ -7,26 +7,40 @@
 
 source Configuration
 
+function checkerror {
+    if [ $? != 0 ]; then
+	echo "Caught error. Exiting."
+	exit 1
+    fi 
+}
+
 #
 mkdir -p ${WORKINGDIR}
 
 # Copy the genomeSets file to the dataDir. This defines named sets of genomes
 # and will have cooresponding buttons in the browser for easy selection.
 cp "${BIN}/genomeSets.tsv" "${WORKINGDIR}/genomeSets.tsv"
+checkerror
 
 # Generate feature files
 ${PYTHON} "${BIN}/getDataFromMouseMine.py" "${WORKINGDIR}"
+checkerror
 
 # Generate synteny blocks
 ${PYTHON} "${BIN}/sb.py" --dir "${WORKINGDIR}" > "${WORKINGDIR}/blocks.tsv"
+checkerror
 
 # Write timestamp
 tsfile="${WORKINGDIR}"/TIMESTAMP.tsv
 echo "TIMESTAMP" > "${tsfile}"
+checkerror
 echo `date` >> "${tsfile}"
+checkerror
 
 # Switcheroo
 mv -f "${OUTDIR}" "${PREVDIR}"
+checkerror
 mv -f "${WORKINGDIR}" "${OUTDIR}"
+checkerror
 
 # THE END
